name: ph3-lab-deploy-S3

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  workflow_authorization:
    name: workflow_authorization
    runs-on: ubuntu-latest
    steps:
       - name: check user permission
         uses: 74th/workflow-permission-action@1.0.0
         with:
           users: vikramk20
           
  build:
    name: build
    runs-on: ubuntu-latest
    needs: workflow_authorization
    steps:
      - name: echo
        run: echo Hello, ${{ inputs.username }}
      - name: Test Secrets
        run: |
          echo Hello, "$ORG"
          if [ "$ORG" == "ORG" ]
          then
            echo "aaa"
          fi
          git clone --depth=1 https://github.com/virtual-labs/ph3-lab-mgmt
          cd ph3-lab-mgmt
          npm install
          npm run labgen -- ../
          cd ../
        env:
          ORG: ${{ secrets.ORG_TEST }}

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
       - name: Deploy
         run: echo Hello, ${{ inputs.username }}
  
