name: ph3-lab-deploy-S3

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  workflow_authorization:
    name: workflow_authorization
    runs-on: ubuntu-latest
    steps:
       - name: check user permission
         uses: 74th/workflow-permission-action@1.0.0
         with:
           users: vikramk20
           
  build:
    name: Ph3 lab build
    runs-on: ubuntu-latest
    needs: workflow_authorization
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node  
        uses: actions/setup-node@v3
        with:
          node-version: 12
          
      - name: Build ph3 lab
        run: |
          git clone --depth=1 https://github.com/virtual-labs/ph3-lab-mgmt
          cd ph3-lab-mgmt
          npm install
          npm run build-lab
          cd ../
          
      - name: Display ph3 lab build files
        run: ls -R build-lab

      - name: Upload ph3 lab artifact
        uses: actions/upload-artifact@master
        with:
          name: ph3-lab
          path: './build'

  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Download ph3 lab artifact
      uses: actions/download-artifact@v2
      with:
        name: ph3-lab
        path: ./ph3-lab

    - name: Display downloaded ph3 lab files
      run: ls -R ph3-lab
      
    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          
    - name: Sync files to S3 bucket
      run: aws s3 cp ph3-lab s3://testgithubvlabs/test --recursive
 
