name: Validate

on:
    workflow_call:

permissions: write-all

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node  
        uses: actions/setup-node@v3
        with:
          node-version: 22
          
      - name: Running Lint Command
        run: |
          echo 'Linting code...'
          #npm i @virtual-labs/buildexp@latest
          npx @virtual-labs/buildexp@latest validate
          echo 'Linting Completed..'
